# Generated by Django 5.1.7 on 2025-04-21 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=100)),
                ('quantite', models.PositiveIntegerField()),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
