# Generated by Django 5.1.7 on 2025-04-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='acheteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vente',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_effectuees', to=settings.AUTH_USER_MODEL),
        ),
    ]
