# Generated by Django 5.1.7 on 2025-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vente_acheteur_alter_vente_vendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
