# Generated by Django 5.2 on 2025-04-22 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categorie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='crypto_prices',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='crypto_prices',
        ),
    ]
